### PR TITLE
[UnoSolver.jl] Replaced Statistics with UnoExecutionStats

### LINKED ISSUE #606: From UNO Statistics to SolverCore
@cvanaret @amontoison First we need to translate the status. I propose:

```julia
"""
$(TYPEDSIGNATURES)

Map Uno termination and solution statuses to SolverCore status symbols.

Converts the combination of Uno's optimization status and solution status into
a single SolverCore-compatible status symbol. This mapping follows Uno's MOI
conventions and ensures compatibility with the CTSolvers pipeline.

# Arguments
- `optimization_status::Cint`: Uno optimization termination status (e.g., `UNO_SUCCESS`, `UNO_ITERATION_LIMIT`)
- `solution_status::Cint`: Uno solution quality status (e.g., `UNO_FEASIBLE_KKT_POINT`, `UNO_UNBOUNDED`)

# Returns
- `Symbol`: SolverCore-compatible status symbol

# Status Mapping

## Termination-based statuses
- `UNO_ITERATION_LIMIT` → `:max_iter`
- `UNO_TIME_LIMIT` → `:max_time`
- `UNO_EVALUATION_ERROR` → `:exception`
- `UNO_ALGORITHMIC_ERROR` → `:exception`
- `UNO_USER_TERMINATION` → `:user`

## Success-based statuses (when `optimization_status == UNO_SUCCESS`)
- `UNO_FEASIBLE_KKT_POINT` → `:first_order`
- `UNO_FEASIBLE_FJ_POINT` → `:first_order`
- `UNO_INFEASIBLE_STATIONARY_POINT` → `:infeasible`
- `UNO_FEASIBLE_SMALL_STEP` → `:small_step`
- `UNO_INFEASIBLE_SMALL_STEP` → `:small_step`
- `UNO_UNBOUNDED` → `:unbounded`
- `UNO_NOT_OPTIMAL` → `:unknown`

# Notes
- The function prioritizes termination status over solution status
- When optimization succeeds, the solution status determines the final status
- This mapping ensures Ipopt-compatible status reporting

See also: [`_uno_to_generic_stats`](@ref)
"""
function _uno_status_to_solvercore(optimization_status::Cint, solution_status::Cint)::Symbol
    if optimization_status == UnoSolver.UNO_ITERATION_LIMIT
        return :max_iter
    elseif optimization_status == UnoSolver.UNO_TIME_LIMIT
        return :max_time
    elseif optimization_status == UnoSolver.UNO_EVALUATION_ERROR
        return :exception
    elseif optimization_status == UnoSolver.UNO_ALGORITHMIC_ERROR
        return :exception
    elseif optimization_status == UnoSolver.UNO_USER_TERMINATION
        return :user
    else # UNO_SUCCESS
        if solution_status == UnoSolver.UNO_FEASIBLE_KKT_POINT
            return :first_order
        elseif solution_status == UnoSolver.UNO_FEASIBLE_FJ_POINT
            return :first_order
        elseif solution_status == UnoSolver.UNO_INFEASIBLE_STATIONARY_POINT
            return :infeasible
        elseif solution_status == UnoSolver.UNO_FEASIBLE_SMALL_STEP
            return :small_step
        elseif solution_status == UnoSolver.UNO_INFEASIBLE_SMALL_STEP
            return :small_step
        elseif solution_status == UnoSolver.UNO_UNBOUNDED
            return :unbounded
        else # UNO_NOT_OPTIMAL
            return :unknown
        end
    end
end
```

then, we need to build a `SolverCore.GenericExecutionStats`:

```julia
"""
$(TYPEDSIGNATURES)

Convert Uno solver statistics to SolverCore generic execution statistics.

Transforms UnoSolver.Statistics into SolverCore.GenericExecutionStats to enable
seamless integration with the CTSolvers pipeline. All fields are marked as reliable
since Uno provides complete statistics.

# Arguments
- `nlp::NLPModels.AbstractNLPModel`: The NLP model that was solved (required for GenericExecutionStats constructor)
- `uno_stats::UnoSolver.Statistics`: Uno solver execution statistics containing solution and performance data

# Returns
- `SolverCore.GenericExecutionStats`: Converted statistics with all fields marked as reliable

# Field Mapping

The following fields are mapped from Uno statistics to GenericExecutionStats:

- `status` ← converted from `optimization_status` and `solution_status` via `_uno_status_to_solvercore`
- `solution` ← `primal_solution`
- `objective` ← `solution_objective`
- `dual_feas` ← `solution_stationarity` (dual feasibility/stationarity residual)
- `primal_feas` ← `solution_primal_feasibility` (constraint violation)
- `multipliers` ← `constraint_dual_solution` (Lagrange multipliers for constraints)
- `multipliers_L` ← `lower_bound_dual_solution` (multipliers for lower bounds)
- `multipliers_U` ← `upper_bound_dual_solution` (multipliers for upper bounds)
- `iter` ← `number_iterations` (converted to Int)
- `elapsed_time` ← `cpu_time`

# Notes
- All fields in the returned GenericExecutionStats are marked as reliable
- Uno-specific information (complementarity, evaluation counts, model, solver) is not preserved
- For full Uno statistics preservation, consider using a specialized UnoExecutionStats type

See also: [`_uno_status_to_solvercore`](@ref), [`solve_with_uno`](@ref)
"""
function _uno_to_generic_stats(
    nlp::NLPModels.AbstractNLPModel, uno_stats::UnoSolver.Statistics
)::SolverCore.GenericExecutionStats
    # Map Uno status to SolverCore status
    status = _uno_status_to_solvercore(
        uno_stats.optimization_status, uno_stats.solution_status
    )

    # Create GenericExecutionStats with all fields marked as reliable
    stats = SolverCore.GenericExecutionStats(
        nlp;
        status=status,
        solution=uno_stats.primal_solution,
        objective=uno_stats.solution_objective,
        dual_feas=uno_stats.solution_stationarity,
        primal_feas=uno_stats.solution_primal_feasibility,
        multipliers=uno_stats.constraint_dual_solution,
        multipliers_L=uno_stats.lower_bound_dual_solution,
        multipliers_U=uno_stats.upper_bound_dual_solution,
        iter=Int(uno_stats.number_iterations),
        elapsed_time=uno_stats.cpu_time,
    )

    return stats
end
```

>[!NOTE]
>Another possibility is to add a `UnoExecutionStats <: SolverCore.AbstractExecutionStats` to save the model and the solver also which will be lost if we use a `SolverCore.GenericExecutionStats`. See the comment below https://github.com/cvanaret/Uno/issues/606#issuecomment-4083897134.

This will be used when `NLPModels` is used and `UnoSolverNLPModelsExt` triggered:

https://github.com/cvanaret/Uno/blob/b7dbdfba95e6d6758bdcbeba3aeb871d65202680/interfaces/Julia/ext/UnoSolverNLPModelsExt/UnoSolverNLPModelsExt.jl#L1

We can replace 

https://github.com/cvanaret/Uno/blob/b7dbdfba95e6d6758bdcbeba3aeb871d65202680/interfaces/Julia/ext/UnoSolverNLPModelsExt/UnoSolverNLPModelsExt.jl#L102-L108

by

```julia
function UnoSolver.uno(nlp::AbstractNLPModel{Float64, Vector{Float64}}; kwargs...)
  model = UnoSolver.uno_model(nlp)
  solver = UnoSolver.uno_solver(; kwargs...)
  UnoSolver.uno_optimize(solver, model)
  stats = UnoSolver.uno_statistics(model, solver)
  return _uno_to_generic_stats(stats)
end
```

We need to add `SolverCore` to the dependences:

https://github.com/cvanaret/Uno/blob/b7dbdfba95e6d6758bdcbeba3aeb871d65202680/interfaces/Julia/Project.toml#L6-L9

The following tests will be useless:

https://github.com/cvanaret/Uno/blob/b7dbdfba95e6d6758bdcbeba3aeb871d65202680/interfaces/Julia/test/NLP_wrapper.jl#L78-L113

https://github.com/cvanaret/Uno/blob/b7dbdfba95e6d6758bdcbeba3aeb871d65202680/interfaces/Julia/test/NLP_wrapper.jl#L162-L197

### PR DESCRIPTION
**Pull request by cvanaret**
cc @ocots @amontoison @cgeoga

close #606

### CODE REVIEW

File: interfaces/Julia/src/C_wrapper.jl [hunk 1]
```diff
@@ -325,63 +325,99 @@ function uno_solver(; kwargs...)
...
+  elseif optimization_status == UNO_TIME_LIMIT
+    status = :max_time
+  elseif optimization_status == UNO_EVALUATION_ERROR
+    status = :exception
+  elseif optimization_status == UNO_ALGORITHMIC_ERROR
+    status = :exception
+  elseif optimization_status == UNO_USER_TERMINATION
+    status = :user
+  else
+    @assert optimization_status == UNO_SUCCESS
```
Comment (ocots) [inline interfaces/Julia/src/C_wrapper.jl:390]: Bien vu !

File: interfaces/Julia/src/C_wrapper.jl [hunk 2]
```diff
@@ -325,63 +325,99 @@ function uno_solver(; kwargs...)
...
+    elseif solution_status == UNO_INFEASIBLE_STATIONARY_POINT
+      status = :infeasible
+    elseif solution_status == UNO_FEASIBLE_SMALL_STEP
+      status = :small_step
+    elseif solution_status == UNO_INFEASIBLE_SMALL_STEP
+      status = :small_step
+    elseif solution_status == UNO_UNBOUNDED
+      status = :unbounded
+    else
+      @assert solution_status == UNO_NOT_OPTIMAL
```
Comment (ocots) [inline interfaces/Julia/src/C_wrapper.jl:404]: Idem.

**Comment by cvanaret** [comment]
@ocots @cgeoga gentle bump :)

**Review by ocots — APPROVED** [review]

**Comment by ocots** [comment]
Everything is fine to me.

**Comment by cgeoga** [comment]
This is great for me as well, thanks @cvanaret! My apologies for the radio silence.

**Comment by cvanaret** [comment]
No worries, thanks for your feedback!

**Comment by amontoison** [comment]
You can release `UnoSolver.jl` v0.3.0 after that.

**Comment by cvanaret** [comment]
[UnoSolver.jl v0.3.0](https://juliahub.com/ui/Packages/General/UnoSolver/0.3.0)

**Comment by ocots** [comment]
@cvanaret New version of Uno taken into account in the future release. See https://github.com/control-toolbox/CTSolvers.jl/pull/124.
